version: '3.8'

services:
  gemini-worker:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: gemini-worker-prod
    ports:
      - "8787:8787"
    volumes:
      # Mount data directory for persistent KV storage
      - ./data:/app/data
    environment:
      # Load environment variables from .env file
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8787/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'